/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package penggajian;

import java.awt.Color;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Set;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import koneksi.koneksidb;

public class kategori extends javax.swing.JFrame {

    public Statement st;
    public ResultSet rs;
    public ResultSet rs1;
    public ResultSet rs2;
    public String kd_karyawan;
    public DefaultTableModel tabModel;
    Connection cn = koneksi.koneksidb.getkoneksi();
    
    public kategori() {
        initComponents();
        tampil_karyawan();
        judul();
        lbl_kode.setVisible(false);
        hapus.setEnabled(false);
        ubah.setEnabled(false);
    }
    public void judul() {
        Object[] judul = {"kd_karyawan","Nama Karyawan","Jabatan","Gaji Pokok","Tunjangan Jabatan","Lembur","Bonus Tambahan","Potongan Pinjaman"};
        tabModel = new DefaultTableModel(null, judul);
        tabel.setModel(tabModel);
    }
    public void reset(){
        lbl_kode.setText("KR000");
        karyawan.setSelectedIndex(0);
        gaji.setText("");
        tunjangan.setText("");
        lembur.setText("");
        bonus.setText("");
        potongan.setText("");
        
        simpan.setEnabled(true);
        hapus.setEnabled(false);
        ubah.setEnabled(false);
    }
    public void tampildata(){
        try{
            st = cn.createStatement();
            tabModel.getDataVector().removeAllElements();
            tabModel.fireTableDataChanged();
            rs = st.executeQuery("SELECT * FROM q_gaji");
            while(rs.next()){
                Object[] data = {
                  rs.getString("kd_karyawan"),
                  rs.getString("nama_karyawan"),
                  rs.getString("jabatan"),
                  rs.getString("gaji_pokok"),
                  rs.getString("tunjangan"),
                  rs.getString("lembur"),
                  rs.getString("bonus"),
                  rs.getString("potongan")
                };
                tabModel.addRow(data);
            }
        }catch(Exception a){
            JOptionPane.showMessageDialog(null, a.getMessage());
        }
    }
    public void tampil_karyawan(){
        try{
            st = cn.createStatement();
            rs1 = st.executeQuery("SELECT * FROM tb_karyawan");
            while(rs1.next()){
                karyawan.addItem(rs1.getString("nama_karyawan"));
            }
        }catch(Exception a) {
            JOptionPane.showMessageDialog(null, a.getMessage());
        }  
    }
    public void setkode(String nama_karyawan){
        try{
            st = cn.createStatement();
            rs2 = st.executeQuery("SELECT * FROM tb_karyawan WHERE nama_karyawan = '"+nama_karyawan+"' ");
            while(rs2.next()){
                kd_karyawan = rs2.getString("kd_karyawan");
            }
        }catch(Exception a){
            JOptionPane.showMessageDialog(null, a.getMessage());
        }
    }
    public String getkode(){
        return kd_karyawan;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        label1 = new java.awt.Label();
        jPanel2 = new javax.swing.JPanel();
        back = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        label2 = new java.awt.Label();
        karyawan = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        gaji = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tunjangan = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        lembur = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        bonus = new javax.swing.JTextField();
        potongan = new javax.swing.JTextField();
        cari = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel = new javax.swing.JTable();
        lbl_kode = new javax.swing.JLabel();
        simpan = new javax.swing.JButton();
        hapus = new javax.swing.JButton();
        ubah = new javax.swing.JButton();
        reset = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(225, 120));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(51, 153, 255));

        label1.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        label1.setForeground(new java.awt.Color(255, 255, 255));
        label1.setText("Input Data Gaji Karyawan");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(0, 102, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(84, 64));
        jPanel2.setRequestFocusEnabled(false);

        back.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        back.setIcon(new javax.swing.ImageIcon("D:\\Icon\\Back To_64px.png")); // NOI18N
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(back, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(back, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setPreferredSize(new java.awt.Dimension(852, 394));

        label2.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        label2.setText("Karyawan");

        karyawan.setBackground(new java.awt.Color(240, 240, 240));
        karyawan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Karyawan" }));
        karyawan.setBorder(null);
        karyawan.setMinimumSize(new java.awt.Dimension(77, 20));
        karyawan.setPreferredSize(new java.awt.Dimension(77, 18));
        karyawan.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                karyawanItemStateChanged(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        jLabel1.setText("Gaji Pokok");

        gaji.setBackground(new java.awt.Color(240, 240, 240));
        gaji.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        gaji.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        gaji.setBorder(null);
        gaji.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                gajiKeyTyped(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        jLabel5.setText("Tunjangan Jabatan");

        tunjangan.setBackground(new java.awt.Color(240, 240, 240));
        tunjangan.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        tunjangan.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tunjangan.setBorder(null);
        tunjangan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tunjanganKeyTyped(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        jLabel7.setText("Lembur");

        lembur.setBackground(new java.awt.Color(240, 240, 240));
        lembur.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        lembur.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        lembur.setBorder(null);
        lembur.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                lemburKeyTyped(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        jLabel6.setText("Bonus Tahunan");

        jLabel8.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        jLabel8.setText("Potongan Pinjaman");

        bonus.setBackground(new java.awt.Color(240, 240, 240));
        bonus.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        bonus.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        bonus.setBorder(null);
        bonus.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                bonusKeyTyped(evt);
            }
        });

        potongan.setBackground(new java.awt.Color(240, 240, 240));
        potongan.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        potongan.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        potongan.setBorder(null);
        potongan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                potonganKeyTyped(evt);
            }
        });

        cari.setBackground(new java.awt.Color(240, 240, 240));
        cari.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        cari.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cari.setBorder(null);
        cari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cariKeyReleased(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(204, 204, 204));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon("D:\\Icon\\Search_32px.png")); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        tabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabel);

        lbl_kode.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_kode.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_kode.setText("KR000");

        simpan.setBackground(new java.awt.Color(23, 32, 41));
        simpan.setForeground(new java.awt.Color(255, 255, 255));
        simpan.setText("Simpan");
        simpan.setBorder(null);
        simpan.setContentAreaFilled(false);
        simpan.setDisabledIcon(new javax.swing.ImageIcon("D:\\Icon\\Unavailable_32px.png")); // NOI18N
        simpan.setOpaque(true);
        simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanActionPerformed(evt);
            }
        });

        hapus.setBackground(new java.awt.Color(23, 32, 41));
        hapus.setForeground(new java.awt.Color(255, 255, 255));
        hapus.setBorder(null);
        hapus.setContentAreaFilled(false);
        hapus.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        hapus.setDisabledIcon(new javax.swing.ImageIcon("D:\\Icon\\Unavailable_32px.png")); // NOI18N
        hapus.setLabel("Hapus");
        hapus.setOpaque(true);
        hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusActionPerformed(evt);
            }
        });

        ubah.setBackground(new java.awt.Color(23, 32, 41));
        ubah.setForeground(new java.awt.Color(255, 255, 255));
        ubah.setText("Ubah");
        ubah.setBorder(null);
        ubah.setContentAreaFilled(false);
        ubah.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/penggajian/Unavailable_32px.png"))); // NOI18N
        ubah.setOpaque(true);
        ubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ubahActionPerformed(evt);
            }
        });

        reset.setBackground(new java.awt.Color(23, 32, 41));
        reset.setForeground(new java.awt.Color(255, 255, 255));
        reset.setText("Reset");
        reset.setBorder(null);
        reset.setContentAreaFilled(false);
        reset.setOpaque(true);
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(gaji, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(karyawan, javax.swing.GroupLayout.Alignment.LEADING, 0, 250, Short.MAX_VALUE)
                    .addComponent(label2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tunjangan, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lembur, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bonus, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(potongan, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(56, 56, 56)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(lbl_kode, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGap(39, 39, 39)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(cari, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 498, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(simpan, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(hapus, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ubah, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(reset, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(23, 23, 23))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)
                        .addComponent(karyawan, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(gaji, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tunjangan, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lembur, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bonus, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cari)
                            .addComponent(lbl_kode, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(simpan, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(hapus, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ubah, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(reset, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(7, 7, 7)))
                .addGap(2, 2, 2)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(potongan, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseClicked
        main_menu menu = new main_menu();
        menu.setVisible(true);
        this.hide();
    }//GEN-LAST:event_backMouseClicked

    private void gajiKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_gajiKeyTyped
        if(!Character.isDigit(evt.getKeyChar())){
            evt.consume();
        }
    }//GEN-LAST:event_gajiKeyTyped

    private void tunjanganKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tunjanganKeyTyped
        if(!Character.isDigit(evt.getKeyChar())){
            evt.consume();
        }
    }//GEN-LAST:event_tunjanganKeyTyped

    private void lemburKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lemburKeyTyped
        if(!Character.isDigit(evt.getKeyChar())){
            evt.consume();
        }
    }//GEN-LAST:event_lemburKeyTyped

    private void bonusKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bonusKeyTyped
        if(!Character.isDigit(evt.getKeyChar())){
            evt.consume();
        }
    }//GEN-LAST:event_bonusKeyTyped

    private void potonganKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_potonganKeyTyped
        if(!Character.isDigit(evt.getKeyChar())){
            evt.consume();
        }
    }//GEN-LAST:event_potonganKeyTyped

    private void karyawanItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_karyawanItemStateChanged
        String nama_karyawan = (String)karyawan.getSelectedItem();
        setkode(nama_karyawan);
        lbl_kode.setText(kd_karyawan);
    }//GEN-LAST:event_karyawanItemStateChanged

    private void simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanActionPerformed
        if(lbl_kode.getText().equals("")|karyawan.getSelectedIndex()==0|gaji.getText().equals("")|tunjangan.getText().equals("")|lembur.getText().equals("")|bonus.getText().equals("")|potongan.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Isi data terlebih dahulu !");
        }else{
            try{
                st = cn.createStatement();
                st.executeUpdate("INSERT INTO tb_gaji VALUES('"+lbl_kode.getText()+"','"+karyawan.getSelectedItem()+"','"+
                    gaji.getText()+"','"+tunjangan.getText()+"','"+lembur.getText()+"','"+bonus.getText()+"','"+
                    potongan.getText()+"') ");
                tampildata();
                reset();
                lbl_kode.setText("KR000");
                JOptionPane.showMessageDialog(null, "Data berhasil di input !");
            }catch(Exception a){
                JOptionPane.showMessageDialog(null, a.getMessage());
            }
        }
    }//GEN-LAST:event_simpanActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        tampildata();
    }//GEN-LAST:event_formWindowOpened

    private void tabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelMouseClicked
        lbl_kode.setText(tabModel.getValueAt(tabel.getSelectedRow(),0)+"");
        karyawan.setSelectedItem(tabModel.getValueAt(tabel.getSelectedRow(),1)+"");
        gaji.setText(tabModel.getValueAt(tabel.getSelectedRow(),3)+"");
        tunjangan.setText(tabModel.getValueAt(tabel.getSelectedRow(),4)+"");
        lembur.setText(tabModel.getValueAt(tabel.getSelectedRow(),5)+"");
        bonus.setText(tabModel.getValueAt(tabel.getSelectedRow(),6)+"");
        potongan.setText(tabModel.getValueAt(tabel.getSelectedRow(),7)+"");
        
        simpan.setEnabled(false);
        hapus.setEnabled(true);
        ubah.setEnabled(true);
    }//GEN-LAST:event_tabelMouseClicked

    private void hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusActionPerformed
        if(lbl_kode.getText().equals("KR000")|karyawan.getSelectedIndex()==0|gaji.getText().equals("")|tunjangan.getText().equals("")|lembur.getText().equals("")|bonus.getText().equals("")|potongan.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Pilih data yang anda maksud !");
        }else{
            try{
                st = cn.createStatement();
                st.executeUpdate("DELETE FROM tb_gaji WHERE kd_karyawan ='"+lbl_kode.getText()+"' ");
                tampildata();
                tampil_karyawan();
                reset();
                JOptionPane.showMessageDialog(null, "Data berhasil di hapus !");
            }catch(Exception a){
                JOptionPane.showMessageDialog(null, a.getMessage());
            }
        }
    }//GEN-LAST:event_hapusActionPerformed

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        reset();
    }//GEN-LAST:event_resetActionPerformed

    private void ubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ubahActionPerformed
        if(lbl_kode.getText().equals("KR000")|karyawan.getSelectedIndex()==0|gaji.getText().equals("")|tunjangan.getText().equals("")|lembur.getText().equals("")|bonus.getText().equals("")|potongan.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Pilih data yang anda maksud !");
        }else{
            try{
                st = cn.createStatement();
                st.executeUpdate("UPDATE tb_gaji set nama_karyawan='"+karyawan.getSelectedItem()+"',gaji_pokok='"+gaji.getText()
                        +"',tunjangan='"+tunjangan.getText()+"',lembur='"+lembur.getText()+"',bonus='"+bonus.getText()
                        +"',potongan='"+potongan.getText()+"' WHERE kd_karyawan='"+lbl_kode.getText()+"' ");
                JOptionPane.showMessageDialog(null, "Data berhasil di ubah !");
                tampildata();
                tampil_karyawan();
                reset();
                lbl_kode.setText("KR000");
            }catch(Exception a){
                JOptionPane.showMessageDialog(null, a.getMessage());
            }
        }
    }//GEN-LAST:event_ubahActionPerformed

    private void cariKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cariKeyReleased
       try{
            st = cn.createStatement();
            tabModel.getDataVector().removeAllElements();
            tabModel.fireTableDataChanged();
            rs = st.executeQuery("SELECT * FROM q_gaji WHERE kd_karyawan like '%"+cari.getText()+"%' or nama_karyawan like '%"+
                cari.getText()+"%' or jabatan like '%"+cari.getText()+"%' or gaji_pokok like '%"+cari.getText()+"%' or tunjangan like '%"+
                cari.getText()+"%' or lembur like '%"+cari.getText()+"%' or bonus like '%"+cari.getText()+"%' or potongan like '%"+cari.getText()+"%' ");
            while(rs.next()){
                Object[] data = {
                    rs.getString("kd_karyawan"),
                    rs.getString("nama_karyawan"),
                    rs.getString("jabatan"),
                    rs.getString("gaji_pokok"),
                    rs.getString("tunjangan"),
                    rs.getString("lembur"),
                    rs.getString("bonus"),
                    rs.getString("potongan"),
                };
                tabModel.addRow(data);
            }
       }catch(Exception a){
           JOptionPane.showMessageDialog(null, a.getMessage());
       }
    }//GEN-LAST:event_cariKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(kategori.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(kategori.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(kategori.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(kategori.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new kategori().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel back;
    private javax.swing.JTextField bonus;
    private javax.swing.JTextField cari;
    private javax.swing.JTextField gaji;
    private javax.swing.JButton hapus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> karyawan;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private javax.swing.JLabel lbl_kode;
    private javax.swing.JTextField lembur;
    private javax.swing.JTextField potongan;
    private javax.swing.JButton reset;
    private javax.swing.JButton simpan;
    private javax.swing.JTable tabel;
    private javax.swing.JTextField tunjangan;
    private javax.swing.JButton ubah;
    // End of variables declaration//GEN-END:variables
}
